version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000" # Map the container port to the host
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount the local configuration file
    # command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]
    command: [ "--model", "huggingface/", "--port", "4000", "--num_workers", "8" ]